name: login
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_localization: ^0.2.0
  intl: any
  country_flags: ^3.0.0
  authen_package:
    path: packages/authen_package
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0